pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
// we are going to add an agent to this stage.  
// Reason : we need a docker image with Go installed to run our Go tests
// Teacher has his own docker image on dockerhub, we will use it, it is called snakee/golang-junit:1.21,
// which means it has Go version 1.21 installed along with junit xml output support.
// Junit will be needed later to run some unit tests. 
// we also add reusenode true to speed up the process by reusing existing containers throughout the pipeline.
        agent {
            docker {
                image 'snakee/golang-junit:1.21' 
                reuseNode true 
            }
        }
//            
            steps {
                dir('bugtracker-backend') {
//                  we add -v which means 'verbose' to see detailed test output
//                  and ./... to run tests in all subdirectories
//                  go being the command to run Go programs 
//                  but we need to wrap it in shell commands.
//
//                  BUT
//                  when I first tried to run the tests as is, in Jenkins environment,
//                  I ran into a golang .cache permissions issue. 
//                  so we use triple single quotes to wrap multiple lines of shell commands    
//                  and set -eux to make the shell exit on errors and print commands as they are executed
//                  I need to set the env variable before running the tests.   
//                  What I added here is to set HOME, GOCACHE and GOMODCACHE to the current working directory
//                  This will ensure that the Go cache and module cache are created in the workspace.            
//                  This should fix the permissions issue.
//                export means to set environment variables in shell.
                    sh ''' 
                    set -eux
                    export HOME="$PWD"
                    export GOCACHE="$PWD/.gocache"
                    export GOMODCACHE="$PWD/.gomodcache"

                    go test -v ./...

                    '''
                }
            }
        }
        stage('Unit Tests - Frontend') {
            agent{
        
                docker {
                    image 'node:20' 
                    reuseNode true 
                }
            }
            steps {
                dir('bugtracker-frontend') {
//                  npm ci will install dependencies based on package-lock.json
//                  npm test will run the tests defined in package.json                
                    sh '''
                    set -eux
                    npm ci
                    npm test
                    '''
                }
            }
        }
    }
}
