pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
// we are going to add an agent to this stage.  
// Reason : we need a docker image with Go installed to run our Go tests
// Teacher has his own docker image on dockerhub, we will use it, it is called snakee/golang-junit:1.21,
// which means it has Go version 1.21 installed along with junit xml output support.
// Junit will be needed later to run some unit tests. 
// we also add reusenode true to speed up the process by reusing existing containers throughout the pipeline.
        agent {
            docker {
                image 'snakee/golang-junit:1.21' 
                reuseNode true 
            }
        }
//            
            steps {
                dir('bugtracker-backend') {
//                  we add -v which means 'verbose' to see detailed test output
//                  and ./... to run tests in all subdirectories
//                  go being the command to run Go programs 
//                  but we need to wrap it in shell commands          
                    sh 'go test -v ./...'
                }
            }
        }
    }
}
