pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            steps {
                dir('bugtracker-backend') {
//                  we add -v which means 'verbose' to see detailed test output
//                  and ./... to run tests in all subdirectories
//                  go being the command to run Go programs          
                    go test -v ./...
                }
            }
        }
    }
}
